name: Sync MoveData Support Documentation

on:
  workflow_dispatch: # Allow manual trigger
  workflow_call: # Allow this workflow to be called by other workflows

env:
  ENVIRONMENT: uat  # Change this variable as needed
  S3_BUCKET_PATH: s3://${{ vars.ENVIRONMENT || 'uat' }}-movedata-ai/support/
  KNOWLEDGE_BASE_ID: IJDF9WCJTI
  KNOWLEDGE_BASE_DATA_SOURCE_ID: GREZAHSG06

jobs:
  sync-documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clean and setup temporary directory
      run: |
        rm -rf ./.tmp
        mkdir ./.tmp
        cd ./.tmp
        mkdir ./extension
        mkdir ./schema

    - name: Clone MoveData support repository
      run: |
        cd ./.tmp
        git clone https://github.com/movedataio/movedata-support.git movedata-support

    - name: Sync documentation branch
      run: |
        cd ./.tmp/movedata-support
        git checkout documentation
        cd ..
        rsync -av --include='*/' --include='*.md' --exclude='*' movedata-support/ ./documentation/

    - name: Sync knowledge base branch
      run: |
        cd ./.tmp/movedata-support
        git checkout knowledgebase
        cd ..
        rsync -av --include='*/' --include='*.md' --exclude='*' movedata-support/ ./knowledgebase/

    - name: Sync developer branch
      run: |
        cd ./.tmp/movedata-support
        git checkout developer
        cd ..
        rsync -av --include='*/' --include='*.md' --exclude='*' movedata-support/ ./developer/

    - name: Sync NPSP fundraising extension
      run: |
        cd ./.tmp/movedata-support
        git checkout extension/npsp-fundraising
        cd ..
        rsync -av --include='*/' --include='*.md' --exclude='*' movedata-support/ ./extension/npsp-fundraising/

    - name: Sync commerce extension
      run: |
        cd ./.tmp/movedata-support
        git checkout extension/commerce
        cd ..
        rsync -av --include='*/' --include='*.md' --exclude='*' movedata-support/ ./extension/commerce/

    - name: Sync Non-Profit Cloud extension
      run: |
        cd ./.tmp/movedata-support
        git checkout extension/non-profit-cloud
        cd ..
        rsync -av --include='*/' --include='*.md' --exclude='*' movedata-support/ ./extension/non-profit-cloud/

    - name: Sync commerce schema
      run: |
        cd ./.tmp/movedata-support
        git checkout schema/commerce
        cd ..
        rsync -av --include='*/' --include='*.md' --exclude='*' movedata-support/ ./schema/commerce/

    - name: Sync donation schema
      run: |
        cd ./.tmp/movedata-support
        git checkout schema/donation
        cd ..
        rsync -av --include='*/' --include='*.md' --exclude='*' movedata-support/ ./schema/donation/

    - name: Clean up cloned repository
      run: |
        rm -rf ./.tmp/movedata-support

    - name: Clear existing S3 content
      run: |
        aws s3 rm s3://${{ env.ENVIRONMENT }}-movedata-ai/support/ --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2

    - name: Sync to S3
      run: |
        aws s3 sync ./.tmp s3://${{ env.ENVIRONMENT }}-movedata-ai/support/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2

    - name: Execute Bedrock Knowledge Base Data Source Sync
      run: |
        aws bedrock-agent start-ingestion-job \
          --knowledge-base-id ${{ env.KNOWLEDGE_BASE_ID }} \
          --data-source-id ${{ env.KNOWLEDGE_BASE_DATA_SOURCE_ID }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-southeast-2