name: Sync MoveData Support Documentation

on:
  workflow_dispatch: # Allow manual trigger
  workflow_call: # Allow this workflow to be called by other workflows
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  ENVIRONMENT: uat  # Change this variable as needed
  S3_BUCKET_PATH: s3://${{ vars.ENVIRONMENT || 'uat' }}-movedata-ai/support/
  KNOWLEDGE_BASE_ID: IJDF9WCJTI
  KNOWLEDGE_BASE_DATA_SOURCE_ID: GREZAHSG06

jobs:
  sync-documentation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v5

      - name: Get Script
        run: |
          curl -o build.ai.sh https://raw.githubusercontent.com/movedataio/movedata-support/main/build.ai.sh
          chmod +x build.ai.sh
        
      - name: Execute Sync Script
        run: ./build.ai.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
          KNOWLEDGE_BASE_ID: ${{ env.KNOWLEDGE_BASE_ID }}
          KNOWLEDGE_BASE_DATA_SOURCE_ID: ${{ env.KNOWLEDGE_BASE_DATA_SOURCE_ID }}
          KNOWLEDGE_BASE_SUPPRESS: ${{ env.KNOWLEDGE_BASE_SUPPRESS }}
          ALGOLIA_APP_ID: ${{ env.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: ${{ env.ALGOLIA_INDEX_NAME }}