name: Sync MoveData Support Documentation

on:
  workflow_call: # Allow this workflow to be called by other workflows
    inputs:
      ENVIRONMENT:
        required: false
        type: string
      KNOWLEDGE_BASE_ID:
        required: false
        type: string
      KNOWLEDGE_BASE_DATA_SOURCE_ID:
        required: false
        type: string
      KNOWLEDGE_BASE_SUPPRESS:
        required: false
        type: string
      ALGOLIA_APP_ID:
        required: false
        type: string
      ALGOLIA_INDEX_NAME:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION: 
        required: true
      ALGOLIA_ADMIN_KEY:
        required: true

env:
  ENVIRONMENT: ${{ inputs.ENVIRONMENT != '' && inputs.ENVIRONMENT || (github.ref == 'refs/heads/main' && 'prod' || 'uat') }}

jobs:
  sync-documentation:
    environment: ${{ inputs.ENVIRONMENT != '' && inputs.ENVIRONMENT || (github.ref == 'refs/heads/main' && 'prod' || 'uat') }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v5

      - name: Get Script
        run: |
          curl -o build.ai.sh https://raw.githubusercontent.com/movedataio/movedata-support/main/build.ai.sh
          chmod +x build.ai.sh
        
      - name: Execute Sync Script
        run: ./build.ai.sh
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          S3_BUCKET_PATH: s3://${{ env.ENVIRONMENT || 'prod' }}-movedata-ai/support/
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          KNOWLEDGE_BASE_ID: ${{ inputs.KNOWLEDGE_BASE_ID != '' && inputs.KNOWLEDGE_BASE_ID || vars.KNOWLEDGE_BASE_ID }}
          KNOWLEDGE_BASE_DATA_SOURCE_ID: ${{ inputs.KNOWLEDGE_BASE_DATA_SOURCE_ID != '' && inputs.KNOWLEDGE_BASE_DATA_SOURCE_ID || vars.KNOWLEDGE_BASE_DATA_SOURCE_ID }}
          KNOWLEDGE_BASE_SUPPRESS: ${{ inputs.KNOWLEDGE_BASE_SUPPRESS != '' && inputs.KNOWLEDGE_BASE_SUPPRESS || vars.KNOWLEDGE_BASE_SUPPRESS }}
          ALGOLIA_APP_ID: ${{ inputs.ALGOLIA_APP_ID != '' && inputs.ALGOLIA_APP_ID || vars.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: ${{ inputs.ALGOLIA_INDEX_NAME != '' && inputs.ALGOLIA_INDEX_NAME || vars.ALGOLIA_INDEX_NAME }}